### ISSUE TITLE
Missing window border

### ISSUE THREAD

**Issue by ctnlaring** [liri-project/liri-player#3]
![screenshot from 2016-01-26 22-01-37](https://cloud.githubusercontent.com/assets/2424846/12603459/7996f116-c478-11e5-86bc-100ccb7efbc5.png)

**Comment by pierremtb** [comment]
There is, a custom one, but the window buttons are currently hidden, I don't know why. I will look into it as soon as I get time. Thank you for your feedbacks !

**Comment by ctnlaring** [comment]
That's fedora 23 workstation with paper gtk theme on gnome 3.

**Comment by ctnlaring** [comment]
@pierremtb I see the buttons when in the "My library" page.

**Comment by ctnlaring** [comment]
Fixed in my pull request #8

**Comment by ctnlaring** [comment]
fixed in 5276bafb05366c881f08657069a2cc2c0a373797
