### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by ctnlaring** [liri-project/liri-player#4]
F11 - toggle fullscreen
Esc - Exit fullscreen
Etc.

**Comment by ctnlaring** [comment]
Fixed in my pull request #8

**Comment by ctnlaring** [comment]
fixed in 5276bafb05366c881f08657069a2cc2c0a373797

**Comment by pierremtb** [comment]
@Collinthegeek Thanks a lot for your contributions :)
